version: '3'
services:
  redis:
    image: redis
    volumes:
       - db_data:/data
  web:
    
    build: .
    ports:
      - "4000:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
volumes:
    db_data: {}
