apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
